### PR TITLE
Enforce function arguments with exception or type-hint

### PR DESCRIPTION
**Pull request by gmazzap**
This PR aim to fix the issues explained in #5.

It does:
- Uses type-hint wherever possible to enforce argument type
- Introduce `UnexpectedValueException` class
- When an unexpected argument is received by a transformer callbacks thows an `UnexpectedValueException`
- Introduce some traits to share methods between `UnexpectedValueException` and `InvalidArgumentException`
- Minor changes to `InvalidArgumentException` messages

### CODE REVIEW

**Comment by tomphp** [comment]
@Giuseppe-Mazzapica Excellent work. Thanks for the contribution. Just 2 small points:
1. can you run `vendor/bin/php-cs-fixer fix src` to correct the coding style issue (and make Travis pass)
2. Any chance of adding some tests for the thrown exceptions?

If you don't have time to do this I'm happy to merge and do it myself, just let me know ;-)

Thanks again.

**Comment by gmazzap** [comment]
@tomphp 
1. I ran php-cs-fixer using my global install, probably I need to update it, but sure no problem
2. Yes, I'll add tests for exceptions later today

**Comment by tomphp** [comment]
@Giuseppe-Mazzapica I want to get this in so I'm going to merge it and add the tests. Many thanks for the contribution!

**Comment by gmazzap** [comment]
Hi @tomphp 

I'm sorry I could not found the time to further work on this, busy days at work and family issues to deal with during weekends...

**Comment by tomphp** [comment]
Hey, no problem at all - your contributions are greatly appreciated!

**Pull request merged**
